# yaml-language-server: $schema=./values.schema.json

global:
  domain: f087b35.kyma.ondemand.com
  imagePullSecret:
    name: docker-registry
  image:
    registry: nicoz91/public-kyma-images
    tag: latest
srv:
  bindings:
    destination:
      serviceInstanceName: 'destination'
  image:
    repository: mockserver-srv
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
destination:
  serviceOfferingName: 'destination'
  servicePlanName: 'lite'
  parameters:
    version: '1.0.0'