# yaml-language-server: $schema=./values.schema.json

global:
  domain: f087b35.kyma.ondemand.com
  imagePullSecret:
    name: docker-registry
  image:
    registry: docker.io/nicoz91/mockserver-srv
    tag: latest
srv:
  bindings:
    destination:
      serviceInstanceName: 'destination'
    db:
      serviceInstanceName: hana
  image:
    repository: mockserver-srv
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
destination:
  serviceOfferingName: 'destination'
  servicePlanName: 'lite'
  parameters:
    version: '1.0.0'
hana-deployer:
  image:
    repository: <your-container-registry>/mockserver-hana-deployer
    tag: latest
  bindings:
    hana:
      serviceInstanceName: hana
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
